allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - icu-minify@4.14.9
  - next-intl-swc-plugin-extractor@4.14.9
  - next-intl@4.14.9
  - use-intl@4.14.9
